# Generated by Django 5.1.2 on 2024-10-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seat',
            field=models.IntegerField(default=0),
        ),
    ]
